import os
import requests

API_TOKEN = os.environ.get('HUGGINGFACEHUB_API_TOKEN')
API_URL = "https://api-inference.huggingface.co/models/mistralai/Mistral-7B-Instruct-v0.2"

def _clean_response(generated_text, prompt):
    """
    Cleans the generated text by removing the specified prompt and any special tokens.

    Args:
        generated_text (str): The text generated by the model which may contain the prompt and special tokens.
        prompt (str): The prompt text that needs to be removed from the generated text.

    Returns:
        str: A cleaned version of the generated text with the prompt and special tokens removed, and each line
             stripped of leading and trailing whitespace.
    """

    cleaned = generated_text.replace(prompt, "").strip()
    cleaned = cleaned.replace("<s>", "").replace("</s>", "").strip()   
    return "\n".join([line.strip() for line in cleaned.split("\n") if line.strip()])

def generate_education_recommendations(input_data, demand_score):
    """
    Generates educational recommendations based on input data and demand score.

    This function creates a prompt with details about the educational data of a specific
    location, including out-of-school rates, literacy rates, enrollment rates, birth rate,
    unemployment rate, and a demand score. The prompt is sent to an external API to generate
    three specific recommendations aimed at improving educational access in the region.

    Args:
        input_data (dict): A dictionary containing key educational metrics and geographic
                           information for the region.
            - Latitude (float): The latitude of the location.
            - Longitude (float): The longitude of the location.
            - OOSR_Primary_Age_Male (float): Out-of-school rate for primary age males.
            - OOSR_Primary_Age_Female (float): Out-of-school rate for primary age females.
            - Youth_15_24_Literacy_Rate_Male (float): Literacy rate for males aged 15-24.
            - Youth_15_24_Literacy_Rate_Female (float): Literacy rate for females aged 15-24.
            - Gross_Primary_Education_Enrollment (float): Gross enrollment rate for primary education.
            - Gross_Tertiary_Education_Enrollment (float): Gross enrollment rate for tertiary education.
            - Birth_Rate (float): Birth rate in the region.
            - Unemployment_Rate (float): Unemployment rate in the region.
        demand_score (float): A demand score representing the educational needs of the region on a scale
                              from 0 to 100.

    Returns:
        str: A string containing three recommendations to improve educational access, formatted
             as a numbered list without additional commentary.
    """

    prompt = f"""
    Analyze this educational data:
    - Location: {input_data['Latitude ']}, {input_data['Longitude']}
    - Primary OOS Rates: Male {input_data['OOSR_Primary_Age_Male']}%, Female {input_data['OOSR_Primary_Age_Female']}%
    - Youth Literacy: Male {input_data['Youth_15_24_Literacy_Rate_Male']}%, Female {input_data['Youth_15_24_Literacy_Rate_Female']}%
    - Enrollment: Primary {input_data['Gross_Primary_Education_Enrollment']}%, Tertiary {input_data['Gross_Tertiary_Education_Enrollment']}%
    - Birth Rate: {input_data['Birth_Rate']}, Unemployment: {input_data['Unemployment_Rate']}%
    - Demand Score: {demand_score}/100

    Generate 3 specific recommendations to improve educational access in this region.
    Provide only the recommendations in numbered list format without any additional commentary.
    """
    
    headers = {"Authorization": f"Bearer {API_TOKEN}"}
    payload = {
        "inputs": prompt,
        "parameters": {
            "max_new_tokens": 300,
            "temperature": 0.7,
            "return_full_text": False 
        }
    }
    
    response = requests.post(API_URL, headers=headers, json=payload)
    generated_text = response.json()[0]['generated_text']
    return _clean_response(generated_text, prompt)

def generate_healthcare_recommendations(input_data, demand_score):
    """
    Generate three specific recommendations to improve healthcare access in a given region.

    Args:
        input_data (dict): A dictionary containing the following information:
            - Latitude (float): The latitude of the location.
            - Longitude (float): The longitude of the location.
            - facilityType (str): The type of facility.
            - facilityOwnerType (str): The owner type of the facility.
        demand_score (float): A demand score representing the healthcare needs of the region on a scale
                              from 0 to 100.

    Returns:
        str: A string containing three recommendations to improve healthcare access, formatted
             as a numbered list without additional commentary.
    """
    prompt = f"""
    Analyze this healthcare data:
    - Location: {input_data['Latitude']}, {input_data['Longitude']}
    - Facility Type: {input_data['facilityType']}
    - Facility Owner: {input_data['facilityOwnerType']}
    - Demand Score: {demand_score}/100

    Generate 3 specific recommendations to improve healthcare access in this region.
    Provide only the recommendations in numbered list format without any additional commentary.
    """
    
    headers = {"Authorization": f"Bearer {API_TOKEN}"}
    payload = {
        "inputs": prompt,
        "parameters": {
            "max_new_tokens": 300,
            "temperature": 0.7,
            "return_full_text": False  # Explicitly request only generated text
        }
    }
    
    response = requests.post(API_URL, headers=headers, json=payload)
    generated_text = response.json()[0]['generated_text']
    return _clean_response(generated_text, prompt)